availproject/avail

.gitignore
Cargo.lock
Cargo.toml
fuzzing/Cargo.toml
fuzzing/README.md
fuzzing/src/build_commitment_fuzz.rs

- created a POC for using AFL as a long running fuzzer for testing individual functions

AVA-87/create-fuzzing-poc

---

kate/src/com.rs

Just a small change which removes possibility to calculate size on block dimensions wrongly, and reduces data duplication in tests.

Replace block dimensions size field with function.

---

Cargo.lock
node/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Bump some version

---

.github/workflows/releaser.yml
.github/workflows/security.yml
Cargo.lock
SECURITY.md
fuzzing/Cargo.toml
node/Cargo.toml
pallets/dactr/Cargo.toml
pallets/mocked_runtime/Cargo.toml
pallets/nomad/da-bridge/Cargo.toml
pallets/nomad/updater-manager/Cargo.toml
pallets/system/src/limits.rs
rpc/kate-rpc-runtime-api/Cargo.toml
rpc/kate-rpc/Cargo.toml
rpc/kate-rpc/src/lib.rs
runtime/src/lib.rs
rustfmt.toml

It seems we pushed into `main`, at some point and forgot `develop`.

Sync from main

---

.dockerignore
Dockerfile
README.md
entrypoint.sh

It fixes https://github.com/maticnetwork/avail/issues/118

Signature mismatch on docker container

---

.github/workflows/releaser.yml
Dockerfile

Dockerfile builds v1.4.0-rc1

---

.github/workflows/default.yml
.github/workflows/releaser.yml
Cargo.lock
Cargo.toml
Dockerfile
README.md
SECURITY.md
fuzzing/scripts/setup.sh
node/Cargo.toml
node/src/command.rs
runtime/Cargo.toml

Remove Polygon refs

---

Dockerfile

- Fixing issue when building docker image (https://github.com/availproject/avail/actions/runs/4755141081/jobs/8504502192#step:7:469) Proposed solution: https://github.com/rust-lang/rustup/issues/2729#issuecomment-1516103534
- Bump avail version.

Fix for "could not rename component file" when building Dockerfile.

---

node/src/chain_spec.rs

Change updater address without referendum.

Updater address change.

---

Dockerfile
entrypoint.sh

Some fixes in the Dockerfile and the `entrypoint.sh`

Dockerfile issues & Telemetry support

---

Cargo.lock
node/Cargo.toml

Avail 1.6.1 rc3

---

examples/validium/abi/ValidiumContract.json
examples/validium/contracts/ValidiumContract.sol

Update examples to match deployed contact that uses keccak256 hashing function.

Update verification contract that uses keccak256.

---

.github/workflows/releaser.yml

Build the wasm binary via srtool and publish it toghether with release.

Add runtime artifact to releaser.

---

fuzzing/scripts/run_afl.sh

Signed-off-by: Harshil Jani <harshiljani2002@gmail.com>

automate rust, substrate, avail, AFL setup

---

Cargo.lock
node/src/chains/common.rs
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/migration.rs

---
name: Pull Request
about: Provide information about the proposed changes
---
Check the [contributing guide](../../CONTRIBUTING.md)

Removed Democracy, Council and Elections pallets

---

.github/workflows/default.yml

Switch back to jlumbroso/free-disk-space in CI

---

Cargo.lock
Cargo.toml
node/Cargo.toml
node/src/service.rs

Enabled offchain_worker functionality to the node

---

Cargo.lock
Cargo.toml
node/Cargo.toml
rpc/kate-rpc/src/lib.rs

Added missing changes from release branches

---

examples/validium/abi/IDataAvailabilityRouter.json
examples/validium/abi/ValidiumContract.json
examples/validium/contracts/ValidiumContract.sol

* fix invalid index bug
* remove redundant variables
* optimize some gas
* convert contract to interface
* remove extraneous function
* add attribution
* update to use open-source license

feat: fix bugs, optimize gas, add attribution

---

runtime/src/constants.rs

removed unused constants

---

node/src/service.rs
pallets/system/src/header_builder.rs
pallets/system/src/offchain.rs

Removed some todos

---

runtime/src/constants.rs
runtime/src/impls.rs
runtime/src/lib.rs

Updated staking and sessions realted constants

---

avail-subxt/src/api_dev.rs

Updated avail subxt

---

node/src/chains/common.rs
pallets/dactr/src/lib.rs
runtime/src/constants.rs

Fixed DA genesis

---

pallets/dactr/src/mock.rs

Fixed DA mock

---

Cargo.lock
Cargo.toml
node/src/chains/common.rs
pallets/system/src/header_builder.rs

For incentivised testnet, loading the pre-generated SRS from a file instead of generating it using rng
- [PR #58](https://github.com/availproject/avail-core/pull/58)

Updated header_builder & dev chains to use new pp

---

avail-subxt/src/primitives/babe.rs
node/src/service.rs
pallets/bridges/nomad/home/src/benchmarking.rs
pallets/mocked_runtime/src/lib.rs
runtime/src/impls.rs

fix a couple of typos

---

rpc/kate-rpc/src/lib.rs

We had erroneously re-introduced loading old pp in the node, because of which the lc verification is failing. This PR loads the new pp again.

Using couscous pp in the node

---

Cargo.lock
Cargo.toml

Added tag refs to avail-core

---

e2e/src/main.rs
examples/deno/api_options.ts
examples/ts/README.md
rpc/kate-rpc/src/lib.rs

Fixes issue with data rows positions in RPC, which breaks commitment equality verification. 
Manual testing, run e2e tests locally.

Fix query rows RPC.

---

examples/validium/common.js

Update validium example to use latest header changes.

Update example to match header changes.

---

runtime/src/impls.rs

made treasury burning to 0%

---

examples/ts/src/submit_proposal.ts

Code Update
- [ ✅ ] Refactor
Changing council proposal to tech comm proposal as council is basically removed
- [ ✅ ] I have performed a self-review of my own code.

update council proposal to tech comm

---

examples/deno/api_options.ts
examples/go/queryProofData/main.go

Updated examples with DataProof type casing

---

examples/validium/contracts/ValidiumContract.sol

Removes additional index check when comparing root hash.

Remove additional index check.

---

examples/validium/submitProof.js

Update validium submit proof.

---

runtime/src/impls.rs
runtime/src/version.rs

update byteFee as per fee model

---

runtime/benches/header_kate_commitment_divan.rs

The benchmarks with Divan now measure throughput of columns using [`IntoCounter` for `u32`](https://docs.rs/divan/0.1/divan/counter/trait.IntoCounter.html#impl-IntoCounter-for-u32) via [`Bencher::counter`](https://docs.rs/divan/0.1/divan/struct.Bencher.html#method.counter). This should be equivalent to using [throughput via Criterion](https://github.com/availproject/avail/blob/863127cb0b300f4a7124e51bc007025d9c399bd7/runtime/benches/header_kate_commitment_cri.rs#L19).
None.
I haven't ran the changes, but given that it's one line for a library I authored (thanks for using it, btw!), I trust it works 😄

Add column throughput to Divan benchmarks

---

examples/deno/benchmarks/query_app_data.ts
examples/deno/benchmarks/query_block_length.ts
examples/deno/benchmarks/query_data_proof.ts
examples/deno/benchmarks/query_proof.ts
examples/deno/benchmarks/query_rows.ts

Updated deno examples

---

node/src/chains/common.rs
pallets/system/src/lib.rs
runtime/src/apis.rs

Closes [#348](https://github.com/availproject/engineering/issues/348)

Remove on-chain storing of SRS

---

README.md

Replaced Kate with Goldberg in our readme file.

---

.github/workflows/releaser.yml
scripts/build_all_linux_flavours.sh
scripts/build_linux_flavours.sh

Changed prebuild binary names

---

avail-subxt/README.md
examples/go/README.md
pallets/system/Cargo.toml

run any example.-->running any example.
with Avail network-->with the Avail network.
extension, purpose--->extensions, purposes.

fix typo in README.md and Cargo.toml

---

.github/workflows/releaser.yml
README.md
examples/deno/README.md

Added Benchmark section to Readme

---

avail-js/examples/next-example/package-lock.json
avail-js/examples/next-example/package.json
avail-js/examples/node-examples/package-lock.json
avail-js/examples/node-examples/package.json
avail-js/package-lock.json
avail-js/package.json
avail-js/src/spec/rpc.ts
avail-js/src/spec/types.ts

update avail-js types

---

.github/workflows/devnet.yml
scripts/purge.sh
scripts/setup.sh
scripts/update-dev-chainspec.py

Added observability to the devnet created by the CI. Earlier it would set up an explorer with the network. Now Prometheus configuration to view the metrics and Promtail configuration to view the logs using a Grafana dashboard is supported in the script.
A tutorial/demo will be posted on how to deploy and test this devnet on Notion.

Added observability to CI devnet

---

pallets/system/src/submitted_data.rs

This PR fixes data root computation on rpc endpoint.

Fix data root computation on blob transactions.

---

pallets/succinct/src/lib.rs
pallets/succinct/src/state.rs
pallets/succinct/src/target_amb.rs
pallets/succinct/src/tests.rs
pallets/succinct/src/verifier.rs

Add code comments, no functional changes

Add code comments, no functional changes

---

misc/genesis/testnet.goldberg.chain.json
misc/genesis/testnet.goldberg.chain.raw.json
node/src/cli.rs

There might be multiple forks at block #344638, this change will help to select the correct one.

Added fork selection for goldberg at block 344638

---

node/src/da_block_import.rs

Fixes BlockImport DA validation bug introduced in 1.9.x.x releases

Fixed da BlockImport validation

---

examples/go/go.mod
examples/go/go.sum

update go to latest avail-gsrpc

---

pallets/vector/src/constants.rs
pallets/vector/src/lib.rs

Fix the period that is emitted in the event once the sync committee hash is updated.
Update to latest period in configuration.

Use correct period in the event. Update dev init constants.

---

pallets/vector/src/tests.rs

Fix broken test after updating period event.

---

node/src/service.rs

Increased grandpa gossip_duration to 1 second

---

pallets/executive/README.md
pallets/transaction-payment/README.md

Added docs on forked pallets

---

avail-js/examples/node-examples/src/query-proof-data.ts

fixed rpc.kate call to query data proof to V2

minor fix to query-data-proof avail-js example

---

avail-subxt/src/api_dev.rs
pallets/vector/src/lib.rs
pallets/vector/src/state.rs

…No functional changes.
Tidy var naming, comments, error codes, and added validation for vk.

Tidy comments, add validation on VK extrinsics and tidy error codes.

---

pallets/dactr/src/benchmarking.rs
pallets/mocked_runtime/src/lib.rs
pallets/vector/src/benchmarking.rs

Fix tests for `--all-features`

---

pallets/dactr/src/benchmarking.rs
pallets/dactr/src/tests.rs
runtime/src/lib.rs

Minor fixes

---

node/src/command.rs

Fixed runtime_benchmarks by adding missing hosted_functions to benchmarking env

Fixed runtime_benchmarks

---

examples/go/queryProofData/main.go

Fix go example

---

.github/workflows/benchmarks.yml

Fix benchmark workflow

---

runtime/src/impls.rs
runtime/src/lib.rs

fix test ci when using -C instrument-coverage

---

Cargo.lock
Cargo.toml
pallets/dactr/src/extensions/check_app_id.rs
runtime/fuzz/header/kate_commit_size.rs

Since only DA submissions are part of the KZG commitments, estimation should be done using only DA submission txs

Fix kate estimation 

---

runtime/src/impls.rs
runtime/src/lib.rs

Added additional calls to existing ProxyType such as:
- `TreasuryCommittee` calls should be part of `Governance`
- `Session` calls should be part of `Staking`

Update Proxy calls for each ProxyType

---

node/src/cli.rs

Not allowing `--unsafe-da-sync` to be used with `--validator` flag

---

examples/go/queryProofData/main.go

fix query_data_proof response

---

examples/go/queryProofData/main.go

fix response w.r.t turing

---

examples/go/record_event/main.go
examples/go/transfer_query_advanced/main.go

add example to read using registry

---

node/src/command.rs
node/src/service.rs
pallets/dactr/src/benchmarking.rs
pallets/dactr/src/extensions/extensions_mock.rs
pallets/dactr/src/mock.rs
pallets/mandate/src/mock.rs
pallets/mocked_runtime/src/lib.rs
pallets/system/benches/bench.rs
pallets/system/benchmarking/src/lib.rs
pallets/system/benchmarking/src/mock.rs
pallets/system/src/lib.rs
pallets/system/src/mock.rs
pallets/system/src/mocking.rs
pallets/system/src/native/build_extension_v1.rs
pallets/system/src/native/build_extension_v2.rs
pallets/system/src/native/hosted_header_builder.rs
pallets/system/src/native/mod.rs
pallets/vector/src/mock.rs
runtime/benches/header_kate_commitment.rs
runtime/src/apis.rs
runtime/src/impls.rs
runtime/src/impls_tests.rs
runtime/src/kate/native.rs

Move files around and made more clear what code is native and what isn't.

Made more clear what code is native

---

Cargo.lock
Cargo.toml
rpc/kate-rpc/src/lib.rs
runtime/Cargo.toml
runtime/src/apis.rs

implemented runtime StakingApi

---

README.md
avail-js/examples/node-examples/package.json
avail-js/examples/readme.md
avail-subxt/README.md

Just made bunch of documentation changes. Nothing code breaking. Should be quick to review. Thanks!
- removed the extra npm scripts command in `avail-js` folder
- improved the docs for the `avail-js` folder
- added links to missing folders or better DevEx

Naruto doc fixes

---

avail-subxt/src/api_dev.rs
pallets/vector/src/lib.rs
pallets/vector/src/state.rs
pallets/vector/src/tests.rs
pallets/vector/src/verifier.rs

This pull request addresses some of the issues found in the audit.
- U256 conversion can cause panic.
- Avoid using default values instead of throwing errors.
- Duplicated condition check in  decode_proof function.
- Unused functions.

Bridge pallet changes

---

runtime/src/version.rs

bumped spec version to 33

---

Cargo.lock
Cargo.toml
base/src/lib.rs
base/src/testing_env.rs
node/Cargo.toml
node/src/rpc.rs
pallets/system/Cargo.toml
pallets/system/src/native/build_extension_v2.rs
rpc/testing-rpc/Cargo.toml
rpc/testing-rpc/src/lib.rs
runtime/Cargo.toml

Closes https://github.com/availproject/engineering/issues/586

Added RPC for custom grid data and testing environment

---

Cargo.lock
Cargo.toml
avail-subxt/Cargo.lock
avail-subxt/Cargo.toml
avail-subxt/src/api_dev.rs
e2e/Cargo.lock
e2e/Cargo.toml
node/src/lib.rs
pallets/dactr/src/benchmarking.rs
pallets/dactr/src/lib.rs
pallets/dactr/src/tests.rs
pallets/dactr/src/weights.rs
pallets/system/src/extensions/check_mortality.rs
pallets/system/src/extensions/check_weight.rs
runtime/src/impls_tests.rs
runtime/src/version.rs
runtime/src/weights/pallet_dactr.rs
scripts/workflows/e2e.sh

Closes https://github.com/availproject/engineering/issues/585

Added custom fees for da call

---

pallets/dactr/src/lib.rs
pallets/vector/src/lib.rs

Removes indexing of both post-inherent & DA transactions

Remove tx indexing

---

avail-js/examples/node-examples/package.json
avail-js/examples/node-examples/src/tx-staking-payout-stakers.ts

Add payout script / example

---

Cargo.lock
avail-js/examples/next-example/package-lock.json
avail-js/examples/next-example/package.json
avail-js/examples/node-examples/package-lock.json
avail-js/examples/node-examples/package.json
avail-js/package-lock.json
avail-js/package.json
avail-subxt/Cargo.lock

wip start fixing dependabot stuff

---

pallets/vector/src/constants.rs

Update Poseidon hash and period.

Update Poseidon hash and period.

---

examples/go/go.mod
examples/go/go.sum
examples/go/properties/main.go

add go examples and new GSRPC tag

---

examples/go/dataSubmitWatch/main.go

- [ ✔️ ] Bugfix
- [ ✔️ ] I have performed a self-review of my own code.

change go events decoder to use events retriver

---

misc/genesis/testnet.turing.chain.spec.json
misc/genesis/testnet.turing.chain.spec.raw.json
node/src/chains/definitions.rs

Added ss58Format property

---

runtime/src/constants.rs
runtime/src/version.rs

Increased block capacity to 5 seconds

---

avail-js/readme.md
pallets/system/README.md
patricia-merkle-trie/README.md

Hello
I found some spelling issues in your docs.
Glad I was helpful.

Fix spelling issue

---

runtime/src/version.rs

bumped runtime version to 37

---

avail-js/docs/README.md
avail-js/docs/extrinsics/balances_tranfer_all.ts
avail-js/docs/extrinsics/balances_tranfer_allow_death.ts
avail-js/docs/extrinsics/balances_tranfer_keep_alive.ts
avail-js/docs/extrinsics/da_create_application_key.ts
avail-js/docs/extrinsics/da_set_aplication_key.ts
avail-js/docs/extrinsics/da_set_submit_data_fee_modifier.ts
avail-js/docs/extrinsics/da_submit_block_length_proposal.ts
avail-js/docs/extrinsics/da_submit_data.ts
avail-js/docs/extrinsics/staking_bond.ts
avail-js/docs/extrinsics/staking_bond_extra.ts
avail-js/docs/extrinsics/staking_chill.ts
avail-js/docs/extrinsics/staking_chill_other.ts
avail-js/docs/extrinsics/staking_nominate.ts
avail-js/docs/extrinsics/staking_unbond.ts
avail-js/docs/extrinsics/staking_validate.ts
avail-js/docs/package-lock.json
avail-js/docs/package.json

update import path in docs example

---

avail-subxt/Cargo.lock

fix subxt-tests

---

avail-deno/src/transactions.ts
avail-js/docs/package-lock.json
avail-js/docs/package.json
avail-js/examples/next-example/package-lock.json
avail-js/examples/next-example/package.json
avail-js/examples/node-examples/package-lock.json
avail-js/examples/node-examples/package.json
avail-js/package.json
avail-js/src/sdk/transactions.ts

Changing typo `unvond` to `unbond` in two places

pushing small typo fix

---

avail-js/docs/README.md

Fix avail-js docs import paths

fix docs import paths

---

avail-js/examples/config.ts
avail-js/examples/node-examples/abi/availbridge.json
avail-js/examples/node-examples/package-lock.json
avail-js/examples/node-examples/package.json
avail-js/examples/node-examples/src/validium.ts
avail-js/examples/node-examples/tsconfig.json
avail-js/examples/readme.md
avail-js/package-lock.json
avail-js/package.json

Add an example of DA attestation using avail js.

Add validium example using avail js.

---

pallets/system/src/limits.rs

Add missing backtick in comment

Add missing backtick in comment

---

runtime/src/constants.rs
runtime/src/version.rs

- Increased MaxBlockCols to 1024
- Increased ideal staking rate to 75%

Updated runtime params

---

pallets/vector/src/benchmarking.rs
pallets/vector/src/lib.rs
pallets/vector/src/tests.rs
pallets/vector/src/weights.rs
runtime/src/weights/pallet_vector.rs

Adds a flag to disable verification on the Vector pallet.

Add verification disabled

---

.github/workflows/releaser_binaries.yml

Referenced the last version of `ghaction-import-gpg`

Pin a newer version of import-gpg
