Cargo.lock
kate/Cargo.toml
kate/proof/Cargo.toml
kate/recovery/Cargo.toml
kate/src/com.rs

This PR adds proof generation and verification to test_build_and_reconstruct. Proof is generated and verified for 1% cells of 20 randomly generated inputs as temporary performance constraint. This should fine starting point to cover most cases in complete encode/reconstruct/generate and verify proof flow. Some of the cases are not covered, like when proof is incorrect and that should be added as separate test later.

Add proof testing to reconstruction test.

---

Cargo.lock
kate/Cargo.toml
kate/src/com.rs
kate/src/lib.rs
node/src/chain_spec.rs
node/src/rpc.rs
pallets/dactr/src/lib.rs
pallets/system/Cargo.toml
pallets/system/src/extensions/check_weight.rs
pallets/system/src/header_builder.rs
pallets/system/src/lib.rs
pallets/system/src/limits.rs
pallets/system/src/migrations.rs
primitives/src/lib.rs
rpc/kate-rpc/src/lib.rs
runtime/src/lib.rs

During the finalization phase of the block creation, we build the kate commitment. This process MUST be infallible, so the preconditions from kate commitment MUST be double-checked before add any TX into the execution queue.
If the kate commitment fails, and the block creation panics and the TX will be included in the next try of block baking. As a result, the entire network will be stuck indefinitely.
Schedule a TX using the schedule pallet to execute a Code Runtime Upgrade and a payload greater than 2.6MB.

Miguel/ava 152 BlockTooBig bug

---

rpc/kate-rpc-runtime-api/src/lib.rs
rpc/kate-rpc/src/lib.rs
runtime/src/lib.rs

The `kate_query_proof` uses the VRF of `Babe`, to reconstruct padding data.
- `BlockLenght` & `PublicParams` are extracted from the requested block (in this rpc) instead of using the latest one.

`kate_query_proof` uses Babe's VRF

---

Cargo.lock
kate/recovery/Cargo.toml
kate/recovery/src/com.rs
kate/src/com.rs

This PR exposes app index (data offsets) in public functions of recovery crate, which enables removal of layout abstraction from avail-light repository.
Notes:
- Naming: struct is named `AppDataIndex` to minimize code changes on avail-light side (since same structure was used there). Struct contains `size` and `index` fields. Since index is already included in struct name, maybe better alternative would be `offsets`. I think its ok to leave it as it is atm since rename is not hard.
- Modules: everything is put under the recovery/com module. We should consider if we want to have separate mod for structs (e.g. `types)`, or some alternative. Also, this will be changed once we agree how to share schemas and code between projects.
- `ExtendedMatrixDimensions` and `AppDataIndex` are passed …

Replace layout with app index in public functions.

---

Cargo.lock
kate/proof/Cargo.toml
kate/proof/src/lib.rs

This PR removes sp-core dependency from kate/proof to decouple avail-light from sp-core version defined in avail project.

Remove sp-core dependency from kate/proof.

---

.github/workflows/releaser.yml
Dockerfile
entrypoint.sh

**linear ticket:** https://linear.app/matic/issue/DVT-139/setup-avail-ci-rust-releaser
**purpose:**
automate avail releases (binaries + docker) with new github actions workflow
this workflow yields the following:
- linux/amd64, centos7/amd64 (for awx compatibility) binaries published directly to avail github releases
- linux/amd64 docker image, published directly to 0xpolygon dockerhub
- all builds run in parallel by leveraging separate github actions jobs (total release time ~40min for all jobs)
**smoke tests:**
to trigger the releaser workflow, a developer simply needs to tag the appropriate commit sha and push as follows: 
`git tag v1.0.0-alpha 517c52e`
`git push origin dan/rust_releaser tag v1.0.0-alpha`
this flow was tested fully, with resulting artifacts now available here:
- …

[DVT-139] avail rust releaser ci integration

---

primitives/src/header.rs

It solves the decoding issue of the header between `subxt` & the node.
**NOTE**:
It requires a complete clean (`cargo clean`) on `avail-subxt` due to changes on `avail.dev.metadata.scale`.

Exposes `Header::Number` as compact type

---

Cargo.lock
primitives/nomad/merkle/Cargo.toml
primitives/nomad/merkle/src/lib.rs
primitives/nomad/merkle/src/light.rs
primitives/nomad/merkle/src/utils.rs
primitives/nomad/nomad-core/src/lib.rs
primitives/nomad/nomad-core/src/nomad_message.rs
primitives/nomad/nomad-core/src/update.rs
primitives/nomad/nomad-core/src/update_v2.rs
primitives/nomad/nomad-core/src/utils.rs
runtime/src/lib.rs

This PR contains minor improvements after Nomad primitives inclusion:
- Use `keccak256_concat` macro to **avoid extra allocations**.
- Replace `lazy_static` by a **pre-build value**. An unit test was added to ensure both are the same value.
- `NomadMessage::to_vec` uses less memory.
- New UT for `NON_BODY_LENGTH` to ensure it is synchronized with `NomadMessage`.

Post nomad primitives PR

---

pallets/system/src/header_builder.rs

- Remove intermediate copies in `build_data_root(...)`
- Use `hex` in UnitTest

Remove intermediate copies & use hex for testing

---

pallets/system/src/lib.rs
pallets/system/src/limits.rs
pallets/system/src/mock.rs
rust-toolchain.toml

It still not compiles, but it merges these files from polkadot-v0.9.29

Update some system files

---

.github/workflows/releaser.yml

Adding a compressed arm build. I don't want to break anything so just testing for now and we can compress the other artifacts later to avoid breaking other automations.

Compressed Binary for CI and aarch64-unknown-linux-gnu Target

---

.github/workflows/releaser.yml

**purpose:** 
compress amd64 binaries to match aarch64
**follow-up**
remove uncompressed amd64 binary once downstream ansible playbooks refactored to unarchive compressed version
**tests:**
smoke tests, successful github actions release run: https://github.com/maticnetwork/avail/actions/runs/3161341290

compress amd64 binary, remove centos7

---

avail-subxt/build_api.sh

The script also downloads the right version of `subxt`.
There is still a PR on parity repo: https://github.com/paritytech/subxt/pull/708

Uses the right version of `subxt`

---

.github/workflows/releaser.yml
.github/workflows/security.yml
SECURITY.md
rustfmt.toml

The current build process was failing and required use of the nightly toolchain. I'm switching to the nightly tool chain in the CI flow and also committing some standard Rust CI workflows from @cvhpoly.
There is  a successful run here: https://github.com/maticnetwork/avail/actions/runs/3431455773
That run created this release: https://github.com/maticnetwork/avail/releases/tag/v1.3.0-2-ad405d0

Switching to Nightly Toolchain

---

Cargo.lock
Cargo.toml
fuzzing/Cargo.toml
node/Cargo.toml
pallets/dactr/Cargo.toml
pallets/mocked_runtime/Cargo.toml
pallets/system/Cargo.toml
rpc/kate-rpc/Cargo.toml
rpc/kate-rpc/src/lib.rs
runtime/Cargo.toml

This PR adds `queryRows` RPC to support fetching and pushing rows to DHT on light clients. Since new RPC is added, node version is increased from 1.4.0 to 1.5.0. Dependency to avail-core will be updated once corresponding PR is merged.

Add kate rows RPC

---

Cargo.lock
Cargo.toml
node/Cargo.toml
node/src/rpc.rs
node/src/service.rs
pallets/dactr/Cargo.toml
pallets/system/src/submitted_data.rs
rpc/kate-rpc/Cargo.toml
rpc/kate-rpc/src/lib.rs

Use `OpaqueExtrinsic` at node binary level. That makes the binary completely agnostic to the underlying runtime.
- [Avail-Core#28](https://github.com/availproject/avail-core/pull/28)
- [Avail-apps#23](https://github.com/availproject/avail-apps/pull/23)
- RPC interfaces need to transform from `OpaqueExtrinsic` into `AppUncheckedExtrinsic` manually, like https://github.com/availproject/avail/blob/381e1539e0829b4c3d6551437c88fc9af32ebd22/rpc/kate-rpc/src/lib.rs#L164

Node binary does not support Runtime Upgrades

---

node/src/chain_spec.rs

Change chain spec to update nomad updater address for devnet. 
This is related to the configuration file: https://github.com/availproject/nomad-config/pull/1/files#diff-98da95bd9dbd4979eaef5e00a61c00e5bb41f0342443a250923582923fadca48R151

Update nomad updater address.

---

avail-subxt/src/primitives/babe.rs
avail-subxt/src/primitives/grandpa.rs

We need this for verification purposes, access outside the crate is private by default. We could perhaps also implement from/into, but this is easier (?)

Enable public access to inner tuple for Grandpa and BABE AccountId.

---

examples/validium/submitProof.js

Use leaf hash from the node query in the example.

Use leaf hash from the node query.

---

pallets/system/src/lib.rs
runtime/src/constants.rs

It fixes the `system::set_code(..)`'s weights, using `max_extrinsic` weight instead of `max_block`.
It also changes 2 things (att @prabal-banerjee ):
- Max Ref Weight for a block has been increased from 2 secs to 5 secs (only in non `fast-runtime`)
- Max Proof Size has been reduced from `u64:MAX` to `500ms`, which we could use in the future to handle `data-root` & `kate-commitment` built.

Fix the `set_code`'s weights

---

pallets/dactr/src/extensions/check_app_id.rs
pallets/system/src/submitted_data.rs
runtime/src/lib.rs

1. It replaces `Option<Vec<Vec<..>>` by `Vec<Vec<..>>`
2. `fn process_call` is simplified by 1

Replace `Option<Vec<Vec<..>>` by `Vec<Vec<..>>`

---

.gitignore
README.md
scripts/run_benchmarks.sh

To improve our lives I have created a simple script that allows us to automate the benchmarking process. The script is quite simple, by default it runs benchmarks for all pallets with steps set to 50 and repeats set to 20.
```bash
./run_benchmarks.sh
```
You can customize the number of steps and repeats for the benchmarks using
environment variables. For example, to set the number of steps to 4 and the
number of repeats to 20, use the following command:
```bash
STEPS=4 REPEAT=20 ./run_benchmarks.sh
```
If you only want to run benchmarks just for our own custom pallets, you can set the
OUR_PALLETS environment variable:
```bash
OUR_PALLETS=1 ./run_benchmarks.sh
```
To run benchmarks for specific pallets, you need to set the PALLETS environment
variable and provide a space-separated list of …

chore: Added script for benchmarking.

---

avail-subxt/Cargo.toml

Since the new versions of sp-* crates have been published recently, it's causing issues in running subxt examples.

Freeze sp-* versions in aligned with subxt

---

Cargo.lock
Cargo.toml
avail-subxt/src/api_dev.rs
runtime/Cargo.toml
runtime/src/apis.rs
runtime/src/lib.rs

A federated naming system, allowing for multiple registrars to be added from a specified origin. Registrars can set a fee to provide identity-verification service. Anyone can put forth a proposed identity for a fixed deposit and ask for review by any number of registrars (paying each of their fees). Registrar judgements are given as an enum, allowing for sophisticated, multi-tier opinions.
Some judgements are identified as sticky, which means they cannot be removed except by complete removal of the identity, or by the registrar. Judgements are allowed to represent a portion of funds that have been reserved for the registrar.
A super-user can remove accounts and in doing so, slash the deposit.
All accounts may also have a limited number of sub-accounts which may be specified by the owner; …

Implemented and activated Identity module

---

Cargo.lock
Cargo.toml
avail-subxt/build_api.sh
avail-subxt/src/api_dev.rs
pallets/system/src/limits.rs

Note: This change is not compatible with the Light Client
avail-core companion: [PR#45](https://github.com/availproject/avail-core/pull/45)
Part of: [Issue #250](https://github.com/availproject/engineering/issues/250)

Updated RPC Response Field Names to Use Camel Case

---

devnet.yml
scripts/consolidate-keys.py
scripts/purge.sh
scripts/setup.sh
scripts/update-dev-chainspec.py

Added a workflow to deploy an ephemeral devnet using the `data-avail` binary built from the latest commit on a PR. This workflow is activated only if a PR has a label attached to it called `deploy-devnet`. Validators, full nodes and light client deployment along with an explorer on a remote server is done by the workflow. 
A few prerequisites have to be setup on the repo level for the workflow to run successfully:-
- **HOST** Github repository secret containing the ip address or the dns of the remote server on which the devnet is going to be deployed.
- **KEY** Github repository secret containing the private ssh key used to login to the server. The corresponding public key should be present in `~/.ssh/authorized_keys` of the remote server.
- **PORT** Github repository secret containing …

Add devnet workflow

---

avail-subxt/src/primitives/header.rs

Currently, when user subscribes to finalized headers using avail-subxt, if there is a need to serialize and store the header, serialized header cannot be deserialized. Reason is different serialization and deserialization type.
This PR changes serialization of a number field in the header defined in the avail-subxt, to a hex number string representation instead of a number, to match deserialization function expectations (and RPC format). 
Tested on [PR](https://github.com/availproject/avail-light/pull/314) which covers described use case.

Serialize block number to hex string on avail_subxt header.

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/01_BUG_REPORT.md
.github/ISSUE_TEMPLATE/02_FEATURE_REQUEST.md

Hello,
**Description and Related Issues:**
I noticed that the file path for the pull request template and contributing was incorrect, so I made the necessary adjustment. The incorrect file path was causing confusion and potentially preventing contributors from accessing the pull request template. 
This pull request fixes the file path issue by changing it from `.//../PULL_REQUEST_TEMPLATE.md` to `./PULL_REQUEST_TEMPLATE.md`and `../../CONTRIBUTING.md` to `/.github/CONTRIBUTING.md`. 
**Type of PR:** Bugfix
**Testing Performed:** I have tested these changes.
Thank you.

Fix Pull Request Template and Contributing Path

---

runtime/Cargo.toml
runtime/benches/header_kate_commitment_divan.rs

This uses [`args`](https://docs.rs/divan/latest/divan/attr.bench.html#args) instead of [`consts`](https://docs.rs/divan/latest/divan/attr.bench.html#consts) to improve compile times.

Use runtime arguments in Divan benchmarks

---

.github/workflows/releaser.yml

`save-state` and `set-output` commands used in GitHub Actions are
deprecated and [GitHub recommends using environment
files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT` fix the warning in github action.
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

ci:Use GITHUB_OUTPUT over set-output command

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/01_BUG_REPORT.md
.github/ISSUE_TEMPLATE/02_FEATURE_REQUEST.md
avail-js/readme.md

Opening an issue template and pressing the contributer guide relative links doesn't work.
For the reporting issue link point to the issue templates.

Fix contributer links

---

pallets/system/src/limits.rs
runtime/src/constants.rs
runtime/src/version.rs

Decreased the block computation capacity by 60%, this will also decrease the DA transaction pricing. (From ~21.5 AVAIL/MB to ~8.5 AVAIL/MB ) and increased the base_weight by 100x to make the min tx cost to 0.1 AVAIL

Decreased block computation capacity

---

pallets/vector/src/lib.rs
pallets/vector/src/tests.rs

* This PR removes the ability for users to send send message fungible token extrinsics with zero amounts
* Added a negative test-case that checks for the relevant error

fix: remove ability to send zero amount fungible token messages

---

e2e/src/main.rs
pallets/dactr/src/kate.rs
pallets/dactr/src/kate/hosted_kate.rs

Kate query_proof RPC was not extending the columns, As a result, we were not able to fetch the proof for extended cells

Fix query_proof RPC

---

avail-subxt/src/avail_client.rs

We're missing a way to connect to the (ordinary) ws, which we use for local testing as well as in CI. This exposes the API to connect to a non-tls node.

Add back insecure url support.

---

e2e/src/main.rs
pallets/system/src/header_builder/version_select.rs
rpc/kate-rpc/src/lib.rs
rpc/kate-rpc/src/metrics.rs

The commitments will be empty with grid dimension [0,0] for blocks without any DA transactions. This is also the case if for any reason [commitment generation fails](https://github.com/availproject/avail/pull/515). In both scenarios, kate `query_rows` and `query_proof` RPCs return an error.

Empty commitments for blocks without any DA extrinsics

---

.github/workflows/releaser_binaries.yml

* bumps checkout action
* adds an ubuntu 22.04 binary for aarch64 architectures

ci: add aarch64 binary for Ubuntu 22.04

---

Cargo.lock
avail-subxt/src/api_dev.rs
pallets/vector/src/benchmarking.rs
pallets/vector/src/lib.rs
pallets/vector/src/tests.rs
pallets/vector/src/weights.rs
runtime/src/weights/pallet_vector.rs

Going forward only preconfigured updater account will be able to call the `fulfill_call` extrinsic.

Added updater to fulfill call

---

avail-go/src/sdk/tx/transactions.go

The transaction data is hardcoded
N/A
I tested a manual transaction 0x10bf32bd3cdf4d6196d2999c7fef36114024fda8fd02eca010ac9d331315b63f to check the content.
- [] The tests pass successfully with `cargo test`.
- [] The code was formatted with `cargo fmt`.
- [] The code compiles with no new warnings with `cargo build --release` and `cargo build --release --features runtime-benchmarks`.
- [] The code has no new warnings when using `cargo clippy`.
- [] If this change affects documented features or needs new documentation, I have created a PR with a [documentation update](https://github.com/availproject/availproject.github.io).

fix: transaction data

---

avail-js/docs/package-lock.json
avail-js/docs/package.json
avail-js/examples/next-example/package-lock.json
avail-js/examples/next-example/package.json
avail-js/examples/node-examples/package-lock.json
avail-js/examples/node-examples/package.json
avail-js/package-lock.json
avail-js/package.json
avail-js/readme.md

update readme for absolute links in avail-js npm registry

---

Cargo.lock
Cargo.toml
node/Cargo.toml
node/src/cli.rs
node/src/command.rs
node/src/lib.rs
node/src/main.rs
node/src/rpc.rs
node/src/service.rs
node/src/transaction_state.rs
pallets/system/rpc/runtime-api/Cargo.toml
pallets/system/rpc/runtime-api/src/lib.rs
rpc/kate-rpc/src/lib.rs
rpc/transaction-rpc/Cargo.toml
rpc/transaction-rpc/src/lib.rs
runtime/src/apis.rs
runtime/src/version.rs

Script to test this feature:
```bash
#!/bin/bash
if [ -z "$1" ]; then
echo "Usage: $0 <transaction_tx>"
exit 1
fi
transaction_tx="$1"
curl -H "Content-Type: application/json" -d "{
\"jsonrpc\": \"2.0\",
\"method\": \"transaction_state\",
\"params\": [\"$transaction_tx\"],
\"id\": 0
}" http://127.0.0.1:9944
echo ""
```

Add Transaction State (Status) RPC

---

.github/workflows/releaser_binaries.yml
README.md

This PR changes the release process by implementing GPG signing for all **binary** artifacts. This allows users to cryptographically verify that binaries were built by our official CI process and haven't been tampered with.
- Added a new `setup_gpg` job that imports our signing key and publishes the public key as a release asset
- Modified all build jobs in the releaser to:
- Generate SHA-256 checksums for each binary
- Create detached GPG signatures for both binaries and checksums
- Upload signatures and checksums to GitHub releases alongside binaries
- Added dependency relationships to ensure signing setup completes before build jobs
- Uses GitHub organization secrets for GPG credentials (key, key ID, and passphrase)
- Pins third-party actions to specific commit hashes for supply chain …

Add binary signing to the releaser
